### ISSUE TITLE
Financial Statement calls broke

### ISSUE THREAD

**Issue by SasquatchPDX** [JerBouma/FundamentalAnalysis#1]
I keep getting the following error, when trying to pull financial statements:
"IndexError: list index out of range"

Here"s the full error for cashflows:

Traceback (most recent call last):
  File "C:/Python/StocksLoader/yFinance_Fundamentals.py", line 10, in <module>
    print(fa.cashflows(symbol))
  File "C:\ProgramData\Anaconda3\envs\StocksLoader\lib\site-packages\FundamentalAnalysis\cashflows.py", line 55, in cashflows
    data = pd.read_html(lxml.etree.tostring(table[0], method='html'))[0].set_index(0).transpose()
IndexError: list index out of range

Ratios, summary, etc... still appear to work.  Any ideas?
Thanks for making this, BTW.

**Comment by antonio-catalano** [comment]
Same here.
I guess that problem is that you must have the Premium account on Yahoo to unlock the "Company Outlook".

**Comment by JerBouma** [comment]
`IndexError: list index out of range`

This error is given because it is unable to find a table on the page (since it is no longer coded this way). For Ratios/Summary, the table still exists.

This is very unfortunate but it seems Yahoo Finance overhauled the entire page. Previously it was as easy as scraping the table that was displayed on that page. I fiddled around with it without any results. For now I lack the time to come up with a proper solution.

Feel free to fiddle around with the code yourself.

**Comment by JerBouma** [comment]
Fully updated the package. Please update your version to use it.
