### ISSUE TITLE
Bug DCF

### ISSUE THREAD

**Issue by ChrisDelClea** [JerBouma/FundamentalAnalysis#26]
Hey guys, 

thanks for this neat package! Srly tho, I have to report a bug.
Not sure if it only affects me, however I checked with the API and it works.
So i figured it has to be some bug in the package: 

If I do 
```
dcf_annually = fa.discounted_cash_flow("XXX", api_key, period="annual")
```
i get: 
```
KeyError                                  
discounted_cash_flow(ticker, api_key, period, limit)
    246 if 'Error Message' in data:
    247     raise ValueError(data['Error Message'])
--> 249 data_json = data[0]['historicalDCF']
    251 data_formatted = {}
    253 if period == "quarter":

KeyError: 'historicalDCF'
```
This occurred for many companies. Could you fix it, if it is related to the package or
otherwise give me some hints, what might have caused this error? 

Best regards 
Chris

**Comment by JerBouma** [comment]
Hi Chris,

I will look at this on Monday. In the mean time, does this also occur for a company like Apple? It could be that the company is simply not available within the FinancialModellingPrep database.

**Comment by ChrisDelClea** [comment]
Hi @JerBouma ,

for apple it works, which is strange, cause they seemed to have changed the URI and added a `-statement`.
I tried with many other companies from the `available_companies()` in the past week and frequently got thrown the same error. So I wonder when to use `historical-discounted-cash-flow`and `historical-discounted-cash-flow-statement` guess there should be difference?

**Comment by ChrisDelClea** [comment]
Update after checking the docs. 

- `historical-discounted-cash-flow-statement` gives back historical data. 
- `discounted-cash-flow` gives back the real time data.
- `historical-discounted-cash-flow/`gives also back historical data with "historicalDCF" (some other json formatting) and is not officially listed in the docs? 

As I found that `historical-discounted-cash-flow-statement` would be the one I would desire. 
Can you double check, @JerBouma?

**Comment by JerBouma** [comment]
I'll look into this and fix it Monday!

**Comment by JerBouma** [comment]
Hey! I think what went wrong is that you tried to collect DCF information on a ticker that wasn't actually a stock but an ETF instead. There is no data available for those objects. I did make the code more robust to be able to try both `historical-discounted-cash-flow` and `historical-discounted-cash-flow-statement`. Because the former gives a larger history, the package will also attempt to use the first one first.

Please update to version 0.2.14 (note that it also should be `import fundamentalanalysis as fa` instead of `import FundamentalAnalysis as fa` now).

**Comment by ChrisDelClea** [comment]
ok thank you.
